theme: jekyll-theme-cayman
title: Curated Recipes for a Discerning Postmodern Palate
google_analytics: UA-37388221-4

relative_links:
  enabled: true
  collections: true

collections:
  recipes:
    output: true
    permalink: /recipes/:name

defaults:
  - scope:
      path: ''
      type: recipes
    values:
      layout: recipe
